const schemaMap = {
  obstetrics: {
    "@context": "https://schema.org",
    "@type": "MedicalClinic",
    "@id": "https://www.drmadhurimsobgyn.com/our-services/obstetrics#clinic",
    name: "Dr Madhuri M S OB-GYN Clinic",
    url: "https://www.drmadhurimsobgyn.com/our-services/obstetrics",
    image: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    logo: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    address: {
      "@type": "PostalAddress",
      streetAddress: "Pattabhirama Nagar, Jayanagar",
      addressLocality: "Bengaluru",
      addressRegion: "Karnataka",
      postalCode: "560041",
      addressCountry: "IN",
    },
    geo: {
      "@type": "GeoCoordinates",
      latitude: "12.9300",
      longitude: "77.5800",
    },
    telephone: "+91 6361197107",
    email: "drmadhuri.og@gmail.com",
    keywords: [
      "Best Obstetrician in Jayanagar",
      "Best maternity clinic in Jayanagar",
      "Best Gynecologist in Jayanagar 7th Block",
      "Diabetes in Pregnancy (GDM) Specialist in Jayanagar 7th Block",
      "Best Gynecologist in Jayanagar 4th Block",
      "Best Gynecologist in Jayanagar 9th block",
    ],
    datePublished: "2025-11-20",
    sameAs: ["https://www.drmadhurimsobgyn.com/"],
  },
  gynaecology: {
    "@context": "https://schema.org",
    "@type": "MedicalClinic",
    "@id": "https://www.drmadhurimsobgyn.com/our-services/gynaecology/#clinic",
    name: "Dr Madhuri M S OB-GYN Clinic",
    url: "https://www.drmadhurimsobgyn.com/our-services/gynaecology",
    image: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    logo: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    address: {
      "@type": "PostalAddress",
      streetAddress: "Pattabhirama Nagar, Jayanagar",
      addressLocality: "Bengaluru",
      addressRegion: "Karnataka",
      postalCode: "560041",
      addressCountry: "IN",
    },
    geo: {
      "@type": "GeoCoordinates",
      latitude: "12.9300",
      longitude: "77.5800",
    },
    telephone: "+91 6361197107",
    email: "drmadhuri.og@gmail.com",
    keywords: [
      "Best maternity clinic in Jayanagar",
      "Best Gynecologist in Jayanagar 7th Block",
      "Diabetes in Pregnancy (GDM) Specialist  in Jayanagar 7th Block",
      "Best Gynecologist in Jayanagar 4th Block",
      "Best Gynecologist in Jayanagar 9th block",
      "Gynaecology Clinic in Jayanagar",
    ],
    datePublished: "2025-11-20",
    sameAs: ["https://www.drmadhurimsobgyn.com/"],
  },
  "obstetrics/antenatal-and-post-natal-care": {
    "@context": "https://schema.org",
    "@type": "MedicalClinic",
    "@id":
      "https://www.drmadhurimsobgyn.com/our-services/obstetrics/antenatal-and-post-natal-care/#clinic",
    name: "Dr Madhuri M S OB-GYN Clinic",
    url: "https://www.drmadhurimsobgyn.com/our-services/obstetrics/antenatal-and-post-natal-care",
    image: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    logo: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    address: {
      "@type": "PostalAddress",
      streetAddress: "Pattabhirama Nagar, Jayanagar",
      addressLocality: "Bengaluru",
      addressRegion: "Karnataka",
      postalCode: "560041",
      addressCountry: "IN",
    },
    geo: {
      "@type": "GeoCoordinates",
      latitude: "12.9300",
      longitude: "77.5800",
    },
    telephone: "+91 6361197107",
    email: "drmadhuri.og@gmail.com",
    keywords: [
      "Best maternity clinic in Jayanagar",
      "Best Gynecologist in Jayanagar 7th Block",
      "Best Gynecologist in Jayanagar 4th Block",
      "Best Gynecologist in Jayanagar 9th block",
      "Comprehensive Antenatal in Jayanagar",
    ],
    datePublished: "2025-11-20",
    sameAs: ["https://www.drmadhurimsobgyn.com/"],
  },
  "obstetrics/high-risk-pregnancy": {
    "@context": "https://schema.org",
    "@type": "MedicalClinic",
    "@id":
      "https://www.drmadhurimsobgyn.com/our-services/obstetrics/high-risk-pregnancy/#clinic",
    name: "Dr Madhuri M S OB-GYN Clinic",
    url: "https://www.drmadhurimsobgyn.com/our-services/obstetrics/high-risk-pregnancy",
    image: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    logo: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    address: {
      "@type": "PostalAddress",
      streetAddress: "Pattabhirama Nagar, Jayanagar",
      addressLocality: "Bengaluru",
      addressRegion: "Karnataka",
      postalCode: "560041",
      addressCountry: "IN",
    },
    geo: {
      "@type": "GeoCoordinates",
      latitude: "12.9300",
      longitude: "77.5800",
    },
    telephone: "+91 6361197107",
    email: "drmadhuri.og@gmail.com",
    keywords: [
      "Best maternity clinic in Jayanagar",
      "Best Gynecologist in Jayanagar 7th Block",
      "Best Gynecologist in Jayanagar 4th Block",
      "Best Gynecologist in Jayanagar 9th block",
      "High Risk Pregnancy Specialist in Jayanagar",
    ],
    datePublished: "2025-11-20",
    sameAs: ["https://www.drmadhurimsobgyn.com/"],
  },
  "obstetrics/previous-cesarean-pregnancy-tolac": {
    "@context": "https://schema.org",
    "@type": "MedicalClinic",
    "@id":
      "https://www.drmadhurimsobgyn.com/our-services/obstetrics/previous-cesarean-pregnancy-tolac/#clinic",
    name: "Dr Madhuri M S OB-GYN Clinic",
    url: "https://www.drmadhurimsobgyn.com/our-services/obstetrics/previous-cesarean-pregnancy-tolac",
    image: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    logo: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    address: {
      "@type": "PostalAddress",
      streetAddress: "Pattabhirama Nagar, Jayanagar",
      addressLocality: "Bengaluru",
      addressRegion: "Karnataka",
      postalCode: "560041",
      addressCountry: "IN",
    },
    geo: {
      "@type": "GeoCoordinates",
      latitude: "12.9300",
      longitude: "77.5800",
    },
    telephone: "+91 6361197107",
    email: "drmadhuri.og@gmail.com",
    keywords: [
      "Best maternity clinic in Jayanagar",
      "Best Gynecologist in Jayanagar 7th Block",
      "Best Gynecologist in Jayanagar 4th Block",
      "Best Gynecologist in Jayanagar 9th block",
      "Pregnancy after C-section treatment in Jayanagar",
    ],
    datePublished: "2025-11-20",
    sameAs: ["https://www.drmadhurimsobgyn.com/"],
  },
  "obstetrics/poor-obstetric-past": {
    "@context": "https://schema.org",
    "@type": "MedicalClinic",
    "@id":
      "https://www.drmadhurimsobgyn.com/our-services/obstetrics/poor-obstetric-past/#clinic",
    name: "Dr Madhuri M S OB-GYN Clinic",
    url: "https://www.drmadhurimsobgyn.com/our-services/obstetrics/poor-obstetric-past",
    image: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    logo: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    address: {
      "@type": "PostalAddress",
      streetAddress: "Pattabhirama Nagar, Jayanagar",
      addressLocality: "Bengaluru",
      addressRegion: "Karnataka",
      postalCode: "560041",
      addressCountry: "IN",
    },
    geo: {
      "@type": "GeoCoordinates",
      latitude: "12.9300",
      longitude: "77.5800",
    },
    telephone: "+91 6361197107",
    email: "drmadhuri.og@gmail.com",
    keywords: [
      "Best maternity clinic in Jayanagar",
      "Best Gynecologist in Jayanagar 7th Block",
      "Best Gynecologist in Jayanagar 4th Block",
      "Best Gynecologist in Jayanagar 9th block",
      "Best Obstetrician in Jayanagar",
    ],
    datePublished: "2025-11-20",
    sameAs: ["https://www.drmadhurimsobgyn.com/"],
  },
  "obstetrics/recurrent-loss-of-pregnancy": {
    "@context": "https://schema.org",
    "@type": "MedicalClinic",
    "@id":
      "https://www.drmadhurimsobgyn.com/our-services/obstetrics/recurrent-loss-of-pregnancy/#clinic",
    name: "Dr Madhuri M S OB-GYN Clinic",
    url: "https://www.drmadhurimsobgyn.com/our-services/obstetrics/recurrent-loss-of-pregnancy",
    image: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    logo: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    address: {
      "@type": "PostalAddress",
      streetAddress: "Pattabhirama Nagar, Jayanagar",
      addressLocality: "Bengaluru",
      addressRegion: "Karnataka",
      postalCode: "560041",
      addressCountry: "IN",
    },
    geo: {
      "@type": "GeoCoordinates",
      latitude: "12.9300",
      longitude: "77.5800",
    },
    telephone: "+91 6361197107",
    email: "drmadhuri.og@gmail.com",
    keywords: [
      "Best maternity clinic in Jayanagar",
      "Best Gynecologist in Jayanagar 7th Block",
      "Best Gynecologist in Jayanagar 4th Block",
      "Best Gynecologist in Jayanagar 9th block",
      "Recurrent Loss of Pregnancy treatment in Jayanagar",
    ],
    datePublished: "2025-11-20",
    sameAs: ["https://www.drmadhurimsobgyn.com/"],
  },
  "obstetrics/diabetes-in-pregnancy-gdm": {
    "@context": "https://schema.org",
    "@type": "MedicalClinic",
    "@id":
      "https://www.drmadhurimsobgyn.com/our-services/obstetrics/diabetes-in-pregnancy-gdm/#clinic",
    name: "Dr Madhuri M S OB-GYN Clinic",
    url: "https://www.drmadhurimsobgyn.com/our-services/obstetrics/diabetes-in-pregnancy-gdm",
    image: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    logo: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    address: {
      "@type": "PostalAddress",
      streetAddress: "Pattabhirama Nagar, Jayanagar",
      addressLocality: "Bengaluru",
      addressRegion: "Karnataka",
      postalCode: "560041",
      addressCountry: "IN",
    },
    geo: {
      "@type": "GeoCoordinates",
      latitude: "12.9300",
      longitude: "77.5800",
    },
    telephone: "+91 6361197107",
    email: "drmadhuri.og@gmail.com",
    keywords: [
      "Best maternity clinic in Jayanagar",
      "Best Gynecologist in Jayanagar 7th Block",
      "Best Gynecologist in Jayanagar 4th Block",
      "Best Gynecologist in Jayanagar 9th block",
      "Diabetes in Pregnancy Treatment in Jayanagar 7th Block Care",
    ],
    datePublished: "2025-11-20",
    sameAs: ["https://www.drmadhurimsobgyn.com/"],
  },
  "obstetrics/hypertension-in-pregnancy-pih": {
    "@context": "https://schema.org",
    "@type": "MedicalClinic",
    "@id":
      "https://www.drmadhurimsobgyn.com/our-services/obstetrics/hypertension-in-pregnancy-pih/#clinic",
    name: "Dr Madhuri M S OB-GYN Clinic",
    url: "https://www.drmadhurimsobgyn.com/our-services/obstetrics/hypertension-in-pregnancy-pih",
    image: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    logo: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    address: {
      "@type": "PostalAddress",
      streetAddress: "Pattabhirama Nagar, Jayanagar",
      addressLocality: "Bengaluru",
      addressRegion: "Karnataka",
      postalCode: "560041",
      addressCountry: "IN",
    },
    geo: {
      "@type": "GeoCoordinates",
      latitude: "12.9300",
      longitude: "77.5800",
    },
    telephone: "+91 6361197107",
    email: "drmadhuri.og@gmail.com",
    keywords: [
      "Best maternity clinic in Jayanagar",
      "Best Gynecologist in Jayanagar 7th Block",
      "Best Gynecologist in Jayanagar 4th Block",
      "Best Gynecologist in Jayanagar 9th block",
      "Hypertension in Pregnancy treatment in Jayanagar",
    ],
    datePublished: "2025-11-20",
    sameAs: ["https://www.drmadhurimsobgyn.com/"],
  },
  "obstetrics/twin-triplet-quadruplet-pregnancy": {
    "@context": "https://schema.org",
    "@type": "MedicalClinic",
    "@id":
      "https://www.drmadhurimsobgyn.com/our-services/obstetrics/twin-triplet-quadruplet-pregnancy/#clinic",
    name: "Dr Madhuri M S OB-GYN Clinic",
    url: "https://www.drmadhurimsobgyn.com/our-services/obstetrics/twin-triplet-quadruplet-pregnancy",
    image: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    logo: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    address: {
      "@type": "PostalAddress",
      streetAddress: "Pattabhirama Nagar, Jayanagar",
      addressLocality: "Bengaluru",
      addressRegion: "Karnataka",
      postalCode: "560041",
      addressCountry: "IN",
    },
    geo: {
      "@type": "GeoCoordinates",
      latitude: "12.9300",
      longitude: "77.5800",
    },
    telephone: "+91 6361197107",
    email: "drmadhuri.og@gmail.com",
    keywords: [
      "Best maternity clinic in Jayanagar",
      "Best Gynecologist in Jayanagar 7th Block",
      "Best Gynecologist in Jayanagar 4th Block",
      "Best Gynecologist in Jayanagar 9th block",
      "Twin pregnancy Specialist in Jayanagar 9th block",
    ],
    datePublished: "2025-11-20",
    sameAs: ["https://www.drmadhurimsobgyn.com/"],
  },
  "obstetrics/multiple-pregnancies": {
    "@context": "https://schema.org",
    "@type": "MedicalClinic",
    "@id":
      "https://www.drmadhurimsobgyn.com/our-services/obstetrics/multiple-pregnancies/#clinic",
    name: "Dr Madhuri M S OB-GYN Clinic",
    url: "https://www.drmadhurimsobgyn.com/our-services/obstetrics/multiple-pregnancies",
    image: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    logo: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    address: {
      "@type": "PostalAddress",
      streetAddress: "Pattabhirama Nagar, Jayanagar",
      addressLocality: "Bengaluru",
      addressRegion: "Karnataka",
      postalCode: "560041",
      addressCountry: "IN",
    },
    geo: {
      "@type": "GeoCoordinates",
      latitude: "12.9300",
      longitude: "77.5800",
    },
    telephone: "+91 6361197107",
    email: "drmadhuri.og@gmail.com",
    keywords: [
      "Best maternity clinic in Jayanagar",
      "Best Gynecologist in Jayanagar 7th Block",
      "Best Gynecologist in Jayanagar 4th Block",
      "Best Gynecologist in Jayanagar 9th block",
      "Multiple birth pregnancy doctor in Jayanagar",
    ],
    datePublished: "2025-11-20",
    sameAs: ["https://www.drmadhurimsobgyn.com/"],
  },
};

export default function Head({ params }) {
  const segs = Array.isArray(params?.["sub-services"]) ? params["sub-services"] : [];
  const pathKey = segs.join("/");
  const jsonLd = schemaMap[pathKey];

  if (!jsonLd) return null;

  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
    />
  );
}
