const schemaMap = {
  obstetrics: {
    "@context": "https://schema.org",
    "@type": "MedicalClinic",
    "@id": "https://www.drmadhurimsobgyn.com/our-services/obstetrics#clinic",
    name: "Dr Madhuri M S OB-GYN Clinic",
    url: "https://www.drmadhurimsobgyn.com/our-services/obstetrics",
    image: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    logo: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    address: {
      "@type": "PostalAddress",
      streetAddress: "Pattabhirama Nagar, Jayanagar",
      addressLocality: "Bengaluru",
      addressRegion: "Karnataka",
      postalCode: "560041",
      addressCountry: "IN",
    },
    geo: {
      "@type": "GeoCoordinates",
      latitude: "12.9300",
      longitude: "77.5800",
    },
    telephone: "+91 6361197107",
    email: "drmadhuri.og@gmail.com",
    keywords: [
      "Best Obstetrician in Jayanagar",
      "Best maternity clinic in Jayanagar",
      "Best Gynecologist in Jayanagar 7th Block",
      "Diabetes in Pregnancy (GDM) Specialist in Jayanagar 7th Block",
      "Best Gynecologist in Jayanagar 4th Block",
      "Best Gynecologist in Jayanagar 9th block",
    ],
    datePublished: "2025-11-20",
    sameAs: ["https://www.drmadhurimsobgyn.com/"],
  },
  gynaecology: {
    "@context": "https://schema.org",
    "@type": "MedicalClinic",
    "@id": "https://www.drmadhurimsobgyn.com/our-services/gynaecology/#clinic",
    name: "Dr Madhuri M S OB-GYN Clinic",
    url: "https://www.drmadhurimsobgyn.com/our-services/gynaecology",
    image: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    logo: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    address: {
      "@type": "PostalAddress",
      streetAddress: "Pattabhirama Nagar, Jayanagar",
      addressLocality: "Bengaluru",
      addressRegion: "Karnataka",
      postalCode: "560041",
      addressCountry: "IN",
    },
    geo: {
      "@type": "GeoCoordinates",
      latitude: "12.9300",
      longitude: "77.5800",
    },
    telephone: "+91 6361197107",
    email: "drmadhuri.og@gmail.com",
    keywords: [
      "Best maternity clinic in Jayanagar",
      "Best Gynecologist in Jayanagar 7th Block",
      "Diabetes in Pregnancy (GDM) Specialist  in Jayanagar 7th Block",
      "Best Gynecologist in Jayanagar 4th Block",
      "Best Gynecologist in Jayanagar 9th block",
      "Gynaecology Clinic in Jayanagar",
    ],
    datePublished: "2025-11-20",
    sameAs: ["https://www.drmadhurimsobgyn.com/"],
  },
  "obstetrics/antenatal-and-post-natal-care": {
    "@context": "https://schema.org",
    "@type": "MedicalClinic",
    "@id":
      "https://www.drmadhurimsobgyn.com/our-services/obstetrics/antenatal-and-post-natal-care/#clinic",
    name: "Dr Madhuri M S OB-GYN Clinic",
    url: "https://www.drmadhurimsobgyn.com/our-services/obstetrics/antenatal-and-post-natal-care",
    image: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    logo: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    address: {
      "@type": "PostalAddress",
      streetAddress: "Pattabhirama Nagar, Jayanagar",
      addressLocality: "Bengaluru",
      addressRegion: "Karnataka",
      postalCode: "560041",
      addressCountry: "IN",
    },
    geo: {
      "@type": "GeoCoordinates",
      latitude: "12.9300",
      longitude: "77.5800",
    },
    telephone: "+91 6361197107",
    email: "drmadhuri.og@gmail.com",
    keywords: [
      "Best maternity clinic in Jayanagar",
      "Best Gynecologist in Jayanagar 7th Block",
      "Best Gynecologist in Jayanagar 4th Block",
      "Best Gynecologist in Jayanagar 9th block",
      "Comprehensive Antenatal in Jayanagar",
    ],
    datePublished: "2025-11-20",
    sameAs: ["https://www.drmadhurimsobgyn.com/"],
  },
  "obstetrics/high-risk-pregnancy": {
    "@context": "https://schema.org",
    "@type": "MedicalClinic",
    "@id":
      "https://www.drmadhurimsobgyn.com/our-services/obstetrics/high-risk-pregnancy/#clinic",
    name: "Dr Madhuri M S OB-GYN Clinic",
    url: "https://www.drmadhurimsobgyn.com/our-services/obstetrics/high-risk-pregnancy",
    image: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    logo: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    address: {
      "@type": "PostalAddress",
      streetAddress: "Pattabhirama Nagar, Jayanagar",
      addressLocality: "Bengaluru",
      addressRegion: "Karnataka",
      postalCode: "560041",
      addressCountry: "IN",
    },
    geo: {
      "@type": "GeoCoordinates",
      latitude: "12.9300",
      longitude: "77.5800",
    },
    telephone: "+91 6361197107",
    email: "drmadhuri.og@gmail.com",
    keywords: [
      "Best maternity clinic in Jayanagar",
      "Best Gynecologist in Jayanagar 7th Block",
      "Best Gynecologist in Jayanagar 4th Block",
      "Best Gynecologist in Jayanagar 9th block",
      "High Risk Pregnancy Specialist in Jayanagar",
    ],
    datePublished: "2025-11-20",
    sameAs: ["https://www.drmadhurimsobgyn.com/"],
  },
  "obstetrics/previous-cesarean-pregnancy-tolac": {
    "@context": "https://schema.org",
    "@type": "MedicalClinic",
    "@id":
      "https://www.drmadhurimsobgyn.com/our-services/obstetrics/previous-cesarean-pregnancy-tolac/#clinic",
    name: "Dr Madhuri M S OB-GYN Clinic",
    url: "https://www.drmadhurimsobgyn.com/our-services/obstetrics/previous-cesarean-pregnancy-tolac",
    image: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    logo: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    address: {
      "@type": "PostalAddress",
      streetAddress: "Pattabhirama Nagar, Jayanagar",
      addressLocality: "Bengaluru",
      addressRegion: "Karnataka",
      postalCode: "560041",
      addressCountry: "IN",
    },
    geo: {
      "@type": "GeoCoordinates",
      latitude: "12.9300",
      longitude: "77.5800",
    },
    telephone: "+91 6361197107",
    email: "drmadhuri.og@gmail.com",
    keywords: [
      "Best maternity clinic in Jayanagar",
      "Best Gynecologist in Jayanagar 7th Block",
      "Best Gynecologist in Jayanagar 4th Block",
      "Best Gynecologist in Jayanagar 9th block",
      "Pregnancy after C-section treatment in Jayanagar",
    ],
    datePublished: "2025-11-20",
    sameAs: ["https://www.drmadhurimsobgyn.com/"],
  },
  "obstetrics/poor-obstetric-past": {
    "@context": "https://schema.org",
    "@type": "MedicalClinic",
    "@id":
      "https://www.drmadhurimsobgyn.com/our-services/obstetrics/poor-obstetric-past/#clinic",
    name: "Dr Madhuri M S OB-GYN Clinic",
    url: "https://www.drmadhurimsobgyn.com/our-services/obstetrics/poor-obstetric-past",
    image: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    logo: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    address: {
      "@type": "PostalAddress",
      streetAddress: "Pattabhirama Nagar, Jayanagar",
      addressLocality: "Bengaluru",
      addressRegion: "Karnataka",
      postalCode: "560041",
      addressCountry: "IN",
    },
    geo: {
      "@type": "GeoCoordinates",
      latitude: "12.9300",
      longitude: "77.5800",
    },
    telephone: "+91 6361197107",
    email: "drmadhuri.og@gmail.com",
    keywords: [
      "Best maternity clinic in Jayanagar",
      "Best Gynecologist in Jayanagar 7th Block",
      "Best Gynecologist in Jayanagar 4th Block",
      "Best Gynecologist in Jayanagar 9th block",
      "Best Obstetrician in Jayanagar",
    ],
    datePublished: "2025-11-20",
    sameAs: ["https://www.drmadhurimsobgyn.com/"],
  },
  "obstetrics/recurrent-loss-of-pregnancy": {
    "@context": "https://schema.org",
    "@type": "MedicalClinic",
    "@id":
      "https://www.drmadhurimsobgyn.com/our-services/obstetrics/recurrent-loss-of-pregnancy/#clinic",
    name: "Dr Madhuri M S OB-GYN Clinic",
    url: "https://www.drmadhurimsobgyn.com/our-services/obstetrics/recurrent-loss-of-pregnancy",
    image: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    logo: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    address: {
      "@type": "PostalAddress",
      streetAddress: "Pattabhirama Nagar, Jayanagar",
      addressLocality: "Bengaluru",
      addressRegion: "Karnataka",
      postalCode: "560041",
      addressCountry: "IN",
    },
    geo: {
      "@type": "GeoCoordinates",
      latitude: "12.9300",
      longitude: "77.5800",
    },
    telephone: "+91 6361197107",
    email: "drmadhuri.og@gmail.com",
    keywords: [
      "Best maternity clinic in Jayanagar",
      "Best Gynecologist in Jayanagar 7th Block",
      "Best Gynecologist in Jayanagar 4th Block",
      "Best Gynecologist in Jayanagar 9th block",
      "Recurrent Loss of Pregnancy treatment in Jayanagar",
    ],
    datePublished: "2025-11-20",
    sameAs: ["https://www.drmadhurimsobgyn.com/"],
  },
  "obstetrics/diabetes-in-pregnancy-gdm": {
    "@context": "https://schema.org",
    "@type": "MedicalClinic",
    "@id":
      "https://www.drmadhurimsobgyn.com/our-services/obstetrics/diabetes-in-pregnancy-gdm/#clinic",
    name: "Dr Madhuri M S OB-GYN Clinic",
    url: "https://www.drmadhurimsobgyn.com/our-services/obstetrics/diabetes-in-pregnancy-gdm",
    image: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    logo: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    address: {
      "@type": "PostalAddress",
      streetAddress: "Pattabhirama Nagar, Jayanagar",
      addressLocality: "Bengaluru",
      addressRegion: "Karnataka",
      postalCode: "560041",
      addressCountry: "IN",
    },
    geo: {
      "@type": "GeoCoordinates",
      latitude: "12.9300",
      longitude: "77.5800",
    },
    telephone: "+91 6361197107",
    email: "drmadhuri.og@gmail.com",
    keywords: [
      "Best maternity clinic in Jayanagar",
      "Best Gynecologist in Jayanagar 7th Block",
      "Best Gynecologist in Jayanagar 4th Block",
      "Best Gynecologist in Jayanagar 9th block",
      "Diabetes in Pregnancy Treatment in Jayanagar 7th Block Care",
    ],
    datePublished: "2025-11-20",
    sameAs: ["https://www.drmadhurimsobgyn.com/"],
  },
  "obstetrics/hypertension-in-pregnancy-pih": {
    "@context": "https://schema.org",
    "@type": "MedicalClinic",
    "@id":
      "https://www.drmadhurimsobgyn.com/our-services/obstetrics/hypertension-in-pregnancy-pih/#clinic",
    name: "Dr Madhuri M S OB-GYN Clinic",
    url: "https://www.drmadhurimsobgyn.com/our-services/obstetrics/hypertension-in-pregnancy-pih",
    image: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    logo: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    address: {
      "@type": "PostalAddress",
      streetAddress: "Pattabhirama Nagar, Jayanagar",
      addressLocality: "Bengaluru",
      addressRegion: "Karnataka",
      postalCode: "560041",
      addressCountry: "IN",
    },
    geo: {
      "@type": "GeoCoordinates",
      latitude: "12.9300",
      longitude: "77.5800",
    },
    telephone: "+91 6361197107",
    email: "drmadhuri.og@gmail.com",
    keywords: [
      "Best maternity clinic in Jayanagar",
      "Best Gynecologist in Jayanagar 7th Block",
      "Best Gynecologist in Jayanagar 4th Block",
      "Best Gynecologist in Jayanagar 9th block",
      "Hypertension in Pregnancy treatment in Jayanagar",
    ],
    datePublished: "2025-11-20",
    sameAs: ["https://www.drmadhurimsobgyn.com/"],
  },
  "obstetrics/twin-triplet-quadruplet-pregnancy": {
    "@context": "https://schema.org",
    "@type": "MedicalClinic",
    "@id":
      "https://www.drmadhurimsobgyn.com/our-services/obstetrics/twin-triplet-quadruplet-pregnancy/#clinic",
    name: "Dr Madhuri M S OB-GYN Clinic",
    url: "https://www.drmadhurimsobgyn.com/our-services/obstetrics/twin-triplet-quadruplet-pregnancy",
    image: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    logo: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    address: {
      "@type": "PostalAddress",
      streetAddress: "Pattabhirama Nagar, Jayanagar",
      addressLocality: "Bengaluru",
      addressRegion: "Karnataka",
      postalCode: "560041",
      addressCountry: "IN",
    },
    geo: {
      "@type": "GeoCoordinates",
      latitude: "12.9300",
      longitude: "77.5800",
    },
    telephone: "+91 6361197107",
    email: "drmadhuri.og@gmail.com",
    keywords: [
      "Best maternity clinic in Jayanagar",
      "Best Gynecologist in Jayanagar 7th Block",
      "Best Gynecologist in Jayanagar 4th Block",
      "Best Gynecologist in Jayanagar 9th block",
      "Twin pregnancy Specialist in Jayanagar 9th block",
    ],
    datePublished: "2025-11-20",
    sameAs: ["https://www.drmadhurimsobgyn.com/"],
  },
  "obstetrics/multiple-pregnancies": {
    "@context": "https://schema.org",
    "@type": "MedicalClinic",
    "@id":
      "https://www.drmadhurimsobgyn.com/our-services/obstetrics/multiple-pregnancies/#clinic",
    name: "Dr Madhuri M S OB-GYN Clinic",
    url: "https://www.drmadhurimsobgyn.com/our-services/obstetrics/multiple-pregnancies",
    image: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    logo: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    address: {
      "@type": "PostalAddress",
      streetAddress: "Pattabhirama Nagar, Jayanagar",
      addressLocality: "Bengaluru",
      addressRegion: "Karnataka",
      postalCode: "560041",
      addressCountry: "IN",
    },
    geo: {
      "@type": "GeoCoordinates",
      latitude: "12.9300",
      longitude: "77.5800",
    },
    telephone: "+91 6361197107",
    email: "drmadhuri.og@gmail.com",
    keywords: [
      "Best maternity clinic in Jayanagar",
      "Best Gynecologist in Jayanagar 7th Block",
      "Best Gynecologist in Jayanagar 4th Block",
      "Best Gynecologist in Jayanagar 9th block",
      "Multiple birth pregnancy doctor in Jayanagar",
    ],
    datePublished: "2025-11-20",
    sameAs: ["https://www.drmadhurimsobgyn.com/"],
  },
  "obstetrics/fetal-growth-restriction": {
    "@context": "https://schema.org",
    "@type": "MedicalClinic",
    "@id":
      "https://www.drmadhurimsobgyn.com/our-services/obstetrics/fetal-growth-restriction/#clinic",
    name: "Dr Madhuri M S OB-GYN Clinic",
    url: "https://www.drmadhurimsobgyn.com/our-services/obstetrics/fetal-growth-restriction",
    image: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    logo: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    address: {
      "@type": "PostalAddress",
      streetAddress: "Pattabhirama Nagar, Jayanagar",
      addressLocality: "Bengaluru",
      addressRegion: "Karnataka",
      postalCode: "560041",
      addressCountry: "IN",
    },
    geo: {
      "@type": "GeoCoordinates",
      latitude: "12.9300",
      longitude: "77.5800",
    },
    telephone: "+91 6361197107",
    email: "drmadhuri.og@gmail.com",
    keywords: [
      "Best maternity clinic in Jayanagar",
      "Best Gynecologist in Jayanagar 7th Block",
      "Diabetes in Pregnancy (GDM) in Jayanagar 7th Block",
      "Best Gynecologist in Jayanagar 4th Block",
      "Best Gynecologist in Jayanagar 9th block",
      "Best Gynecologist in Jayanagar",
    ],
    datePublished: "2025-11-26",
    sameAs: ["https://www.drmadhurimsobgyn.com/"],
  },
  infertility: {
    "@context": "https://schema.org",
    "@type": "MedicalClinic",
    "@id": "https://www.drmadhurimsobgyn.com/our-services/infertility/#clinic",
    name: "Dr Madhuri M S OB-GYN Clinic",
    url: "https://www.drmadhurimsobgyn.com/our-services/infertility",
    image: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    logo: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    address: {
      "@type": "PostalAddress",
      streetAddress: "Pattabhirama Nagar, Jayanagar",
      addressLocality: "Bengaluru",
      addressRegion: "Karnataka",
      postalCode: "560041",
      addressCountry: "IN",
    },
    geo: {
      "@type": "GeoCoordinates",
      latitude: "12.9300",
      longitude: "77.5800",
    },
    telephone: "+91 6361197107",
    email: "drmadhuri.og@gmail.com",
    keywords: [
      "Best maternity clinic in Jayanagar",
      "Best Gynecologist in Jayanagar 7th Block",
      "Diabetes in Pregnancy (GDM) in Jayanagar 7th Block",
      "Best Gynecologist in Jayanagar 4th Block",
      "Best Gynecologist in Jayanagar 9th block",
      "Infertility specialist in Jayanagar 7th Block",
    ],
    datePublished: "2025-11-26",
    sameAs: ["https://www.drmadhurimsobgyn.com/"],
  },
  "infertility/complete-evaluation": {
    "@context": "https://schema.org",
    "@type": "MedicalClinic",
    "@id":
      "https://www.drmadhurimsobgyn.com/our-services/infertility/complete-evaluation/#clinic",
    name: "Dr Madhuri M S OB-GYN Clinic",
    url: "https://www.drmadhurimsobgyn.com/our-services/infertility/complete-evaluation",
    image: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    logo: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    address: {
      "@type": "PostalAddress",
      streetAddress: "Pattabhirama Nagar, Jayanagar",
      addressLocality: "Bengaluru",
      addressRegion: "Karnataka",
      postalCode: "560041",
      addressCountry: "IN",
    },
    geo: {
      "@type": "GeoCoordinates",
      latitude: "12.9300",
      longitude: "77.5800",
    },
    telephone: "+91 6361197107",
    email: "drmadhuri.og@gmail.com",
    keywords: [
      "Best maternity clinic in Jayanagar",
      "Best Gynecologist in Jayanagar 7th Block",
      "Diabetes in Pregnancy (GDM) in Jayanagar 7th Block",
      "Best Gynecologist in Jayanagar 4th Block",
      "Best Gynecologist in Jayanagar 9th block",
      "Best infertility clinic in jayanagar 4th Block",
    ],
    datePublished: "2025-11-26",
    sameAs: ["https://www.drmadhurimsobgyn.com/"],
  },
  "infertility/ovulation-induction": {
    "@context": "https://schema.org",
    "@type": "MedicalClinic",
    "@id":
      "https://www.drmadhurimsobgyn.com/our-services/infertility/ovulation-induction/#clinic",
    name: "Dr Madhuri M S OB-GYN Clinic",
    url: "https://www.drmadhurimsobgyn.com/our-services/infertility/ovulation-induction",
    image: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    logo: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    address: {
      "@type": "PostalAddress",
      streetAddress: "Pattabhirama Nagar, Jayanagar",
      addressLocality: "Bengaluru",
      addressRegion: "Karnataka",
      postalCode: "560041",
      addressCountry: "IN",
    },
    geo: {
      "@type": "GeoCoordinates",
      latitude: "12.9300",
      longitude: "77.5800",
    },
    telephone: "+91 6361197107",
    email: "drmadhuri.og@gmail.com",
    keywords: [
      "Best maternity clinic in Jayanagar",
      "Best Gynecologist in Jayanagar 7th Block",
      "Diabetes in Pregnancy (GDM) in Jayanagar 7th Block",
      "Best Gynecologist in Jayanagar 4th Block",
      "Best Gynecologist in Jayanagar 9th block",
      "Ovulation induction treatment in Jayanagar",
    ],
    datePublished: "2025-11-26",
    sameAs: ["https://www.drmadhurimsobgyn.com/"],
  },
  "infertility/intra-uterine-insemination-iui": {
    "@context": "https://schema.org",
    "@type": "MedicalClinic",
    "@id":
      "https://www.drmadhurimsobgyn.com/our-services/infertility/intra-uterine-insemination-iui/#clinic",
    name: "Dr Madhuri M S OB-GYN Clinic",
    url: "https://www.drmadhurimsobgyn.com/our-services/infertility/intra-uterine-insemination-iui",
    image: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    logo: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    address: {
      "@type": "PostalAddress",
      streetAddress: "Pattabhirama Nagar, Jayanagar",
      addressLocality: "Bengaluru",
      addressRegion: "Karnataka",
      postalCode: "560041",
      addressCountry: "IN",
    },
    geo: {
      "@type": "GeoCoordinates",
      latitude: "12.9300",
      longitude: "77.5800",
    },
    telephone: "+91 6361197107",
    email: "drmadhuri.og@gmail.com",
    keywords: [
      "Best maternity clinic in Jayanagar",
      "Best Gynecologist in Jayanagar 7th Block",
      "Diabetes in Pregnancy (GDM) in Jayanagar 7th Block",
      "Best Gynecologist in Jayanagar 4th Block",
      "Best Gynecologist in Jayanagar 9th block",
      "Best Intra-Uterine Insemination center in Jayanagar",
    ],
    datePublished: "2025-11-26",
    sameAs: ["https://www.drmadhurimsobgyn.com/"],
  },
  "gynaecology/fibroids-leiomyoma-of-uterus": {
    "@context": "https://schema.org",
    "@type": "MedicalClinic",
    "@id":
      "https://www.drmadhurimsobgyn.com/our-services/gynaecology/fibroids-leiomyoma-of-uterus/#clinic",
    name: "Dr Madhuri M S OB-GYN Clinic",
    url: "https://www.drmadhurimsobgyn.com/our-services/gynaecology/fibroids-leiomyoma-of-uterus",
    image: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    logo: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    address: {
      "@type": "PostalAddress",
      streetAddress: "Pattabhirama Nagar, Jayanagar",
      addressLocality: "Bengaluru",
      addressRegion: "Karnataka",
      postalCode: "560041",
      addressCountry: "IN",
    },
    geo: {
      "@type": "GeoCoordinates",
      latitude: "12.9300",
      longitude: "77.5800",
    },
    telephone: "+91 6361197107",
    email: "drmadhuri.og@gmail.com",
    keywords: [
      "Best maternity clinic in Jayanagar",
      "Best Gynecologist in Jayanagar 7th Block",
      "Diabetes in Pregnancy (GDM) in Jayanagar 7th Block",
      "Best Gynecologist in Jayanagar 4th Block",
      "Best Gynecologist in Jayanagar 9th block",
      "Uterine fibroid treatment in Jayanagar 9th Block",
    ],
    datePublished: "2025-11-26",
    sameAs: ["https://www.drmadhurimsobgyn.com/"],
  },
  "gynaecology/fibroids-of-cervix": {
    "@context": "https://schema.org",
    "@type": "MedicalClinic",
    "@id":
      "https://www.drmadhurimsobgyn.com/our-services/gynaecology/fibroids-of-cervix/#clinic",
    name: "Dr Madhuri M S OB-GYN Clinic",
    url: "https://www.drmadhurimsobgyn.com/our-services/gynaecology/fibroids-of-cervix",
    image: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    logo: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    address: {
      "@type": "PostalAddress",
      streetAddress: "Pattabhirama Nagar, Jayanagar",
      addressLocality: "Bengaluru",
      addressRegion: "Karnataka",
      postalCode: "560041",
      addressCountry: "IN",
    },
    geo: {
      "@type": "GeoCoordinates",
      latitude: "12.9300",
      longitude: "77.5800",
    },
    telephone: "+91 6361197107",
    email: "drmadhuri.og@gmail.com",
    keywords: [
      "Best maternity clinic in Jayanagar",
      "Best Gynecologist in Jayanagar 7th Block",
      "Diabetes in Pregnancy (GDM) in Jayanagar 7th Block",
      "Best Gynecologist in Jayanagar 4th Block",
      "Best Gynecologist in Jayanagar 9th block",
      "Fibroid Treatment in Jayanagar 7th Block",
    ],
    datePublished: "2025-11-26",
    sameAs: ["https://www.drmadhurimsobgyn.com/"],
  },
  "gynaecology/abnormal-dysfunctional-uterus-bleeding": {
    "@context": "https://schema.org",
    "@type": "MedicalClinic",
    "@id":
      "https://www.drmadhurimsobgyn.com/our-services/gynaecology/abnormal-dysfunctional-uterus-bleeding/#clinic",
    name: "Dr Madhuri M S OB-GYN Clinic",
    url: "https://www.drmadhurimsobgyn.com/our-services/gynaecology/abnormal-dysfunctional-uterus-bleeding",
    image: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    logo: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    address: {
      "@type": "PostalAddress",
      streetAddress: "Pattabhirama Nagar, Jayanagar",
      addressLocality: "Bengaluru",
      addressRegion: "Karnataka",
      postalCode: "560041",
      addressCountry: "IN",
    },
    geo: {
      "@type": "GeoCoordinates",
      latitude: "12.9300",
      longitude: "77.5800",
    },
    telephone: "+91 6361197107",
    email: "drmadhuri.og@gmail.com",
    keywords: [
      "Best maternity clinic in Jayanagar",
      "Best Gynecologist in Jayanagar 7th Block",
      "Diabetes in Pregnancy (GDM) in Jayanagar 7th Block",
      "Best Gynecologist in Jayanagar 4th Block",
      "Best Gynecologist in Jayanagar 9th block",
      "Uterine bleeding treatment in Jayanagar",
    ],
    datePublished: "2025-11-26",
    sameAs: ["https://www.drmadhurimsobgyn.com/"],
  },
  "gynaecology/endometriosis": {
    "@context": "https://schema.org",
    "@type": "MedicalClinic",
    "@id":
      "https://www.drmadhurimsobgyn.com/our-services/gynaecology/endometriosis/#clinic",
    name: "Dr Madhuri M S OB-GYN Clinic",
    url: "https://www.drmadhurimsobgyn.com/our-services/gynaecology/endometriosis",
    image: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    logo: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    address: {
      "@type": "PostalAddress",
      streetAddress: "Pattabhirama Nagar, Jayanagar",
      addressLocality: "Bengaluru",
      addressRegion: "Karnataka",
      postalCode: "560041",
      addressCountry: "IN",
    },
    geo: {
      "@type": "GeoCoordinates",
      latitude: "12.9300",
      longitude: "77.5800",
    },
    telephone: "+91 6361197107",
    email: "drmadhuri.og@gmail.com",
    keywords: [
      "Best maternity clinic in Jayanagar",
      "Best Gynecologist in Jayanagar 7th Block",
      "Diabetes in Pregnancy (GDM) in Jayanagar 7th Block",
      "Best Gynecologist in Jayanagar 4th Block",
      "Best Gynecologist in Jayanagar 9th block",
      "Best gynecologist for endometriosis in Jayanagar",
    ],
    datePublished: "2025-11-26",
    sameAs: ["https://www.drmadhurimsobgyn.com/"],
  },
  "gynaecology/ovarian-cysts": {
    "@context": "https://schema.org",
    "@type": "MedicalClinic",
    "@id":
      "https://www.drmadhurimsobgyn.com/our-services/gynaecology/ovarian-cysts/#clinic",
    name: "Dr Madhuri M S OB-GYN Clinic",
    url: "https://www.drmadhurimsobgyn.com/our-services/gynaecology/ovarian-cysts",
    image: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    logo: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    address: {
      "@type": "PostalAddress",
      streetAddress: "Pattabhirama Nagar, Jayanagar",
      addressLocality: "Bengaluru",
      addressRegion: "Karnataka",
      postalCode: "560041",
      addressCountry: "IN",
    },
    geo: {
      "@type": "GeoCoordinates",
      latitude: "12.9300",
      longitude: "77.5800",
    },
    telephone: "+91 6361197107",
    email: "drmadhuri.og@gmail.com",
    keywords: [
      "Best maternity clinic in Jayanagar",
      "Best Gynecologist in Jayanagar 7th Block",
      "Diabetes in Pregnancy (GDM) in Jayanagar 7th Block",
      "Best Gynecologist in Jayanagar 4th Block",
      "Best Gynecologist in Jayanagar 9th block",
      "Best hospital for ovarian cyst in Jayanagar 4th Block",
    ],
    datePublished: "2025-11-26",
    sameAs: ["https://www.drmadhurimsobgyn.com/"],
  },
  "gynaecology/chocolate-cyst-endometrioma-of-ovary": {
    "@context": "https://schema.org",
    "@type": "MedicalClinic",
    "@id":
      "https://www.drmadhurimsobgyn.com/our-services/gynaecology/chocolate-cyst-endometrioma-of-ovary/#clinic",
    name: "Dr Madhuri M S OB-GYN Clinic",
    url: "https://www.drmadhurimsobgyn.com/our-services/gynaecology/chocolate-cyst-endometrioma-of-ovary",
    image: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    logo: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    address: {
      "@type": "PostalAddress",
      streetAddress: "Pattabhirama Nagar, Jayanagar",
      addressLocality: "Bengaluru",
      addressRegion: "Karnataka",
      postalCode: "560041",
      addressCountry: "IN",
    },
    geo: {
      "@type": "GeoCoordinates",
      latitude: "12.9300",
      longitude: "77.5800",
    },
    telephone: "+91 6361197107",
    email: "drmadhuri.og@gmail.com",
    keywords: [
      "Best maternity clinic in Jayanagar",
      "Best Gynecologist in Jayanagar 7th Block",
      "Diabetes in Pregnancy (GDM) in Jayanagar 7th Block",
      "Best Gynecologist in Jayanagar 4th Block",
      "Best Gynecologist in Jayanagar 9th block",
      "Chocolate cyst treatment in Jayanagar 4th Block",
    ],
    datePublished: "2025-11-28",
    sameAs: ["https://www.drmadhurimsobgyn.com/"],
  },
  "gynaecology/hormone-imbalances": {
    "@context": "https://schema.org",
    "@type": "MedicalClinic",
    "@id":
      "https://www.drmadhurimsobgyn.com/our-services/gynaecology/hormone-imbalances/#clinic",
    name: "Dr Madhuri M S OB-GYN Clinic",
    url: "https://www.drmadhurimsobgyn.com/our-services/gynaecology/hormone-imbalances",
    image: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    logo: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    address: {
      "@type": "PostalAddress",
      streetAddress: "Pattabhirama Nagar, Jayanagar",
      addressLocality: "Bengaluru",
      addressRegion: "Karnataka",
      postalCode: "560041",
      addressCountry: "IN",
    },
    geo: {
      "@type": "GeoCoordinates",
      latitude: "12.9300",
      longitude: "77.5800",
    },
    telephone: "+91 6361197107",
    email: "drmadhuri.og@gmail.com",
    keywords: [
      "Best maternity clinic in Jayanagar",
      "Best Gynecologist in Jayanagar 7th Block",
      "Diabetes in Pregnancy (GDM) in Jayanagar 7th Block",
      "Best Gynecologist in Jayanagar 4th Block",
      "Best Gynecologist in Jayanagar 9th block",
      "Hormone Imbalance Treatment in Jayanagar",
    ],
    datePublished: "2025-11-28",
    sameAs: ["https://www.drmadhurimsobgyn.com/"],
  },
  "gynaecology/severe-pelvic-pain-management": {
    "@context": "https://schema.org",
    "@type": "MedicalClinic",
    "@id":
      "https://www.drmadhurimsobgyn.com/our-services/gynaecology/severe-pelvic-pain-management/#clinic",
    name: "Dr Madhuri M S OB-GYN Clinic",
    url: "https://www.drmadhurimsobgyn.com/our-services/gynaecology/severe-pelvic-pain-management",
    image: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    logo: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    address: {
      "@type": "PostalAddress",
      streetAddress: "Pattabhirama Nagar, Jayanagar",
      addressLocality: "Bengaluru",
      addressRegion: "Karnataka",
      postalCode: "560041",
      addressCountry: "IN",
    },
    geo: {
      "@type": "GeoCoordinates",
      latitude: "12.9300",
      longitude: "77.5800",
    },
    telephone: "+91 6361197107",
    email: "drmadhuri.og@gmail.com",
    keywords: [
      "Best maternity clinic in Jayanagar",
      "Best Gynecologist in Jayanagar 7th Block",
      "Diabetes in Pregnancy (GDM) in Jayanagar 7th Block",
      "Best Gynecologist in Jayanagar 4th Block",
      "Best Gynecologist in Jayanagar 9th block",
      "Pelvic Pain Specialists in Jayanagar",
    ],
    datePublished: "2025-11-28",
    sameAs: ["https://www.drmadhurimsobgyn.com/"],
  },
  "gynaecology/menopausal-and-perimenopausal-care": {
    "@context": "https://schema.org",
    "@type": "MedicalClinic",
    "@id":
      "https://www.drmadhurimsobgyn.com/our-services/gynaecology/menopausal-and-perimenopausal-care/#clinic",
    name: "Dr Madhuri M S OB-GYN Clinic",
    url: "https://www.drmadhurimsobgyn.com/our-services/gynaecology/menopausal-and-perimenopausal-care",
    image: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    logo: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    address: {
      "@type": "PostalAddress",
      streetAddress: "Pattabhirama Nagar, Jayanagar",
      addressLocality: "Bengaluru",
      addressRegion: "Karnataka",
      postalCode: "560041",
      addressCountry: "IN",
    },
    geo: {
      "@type": "GeoCoordinates",
      latitude: "12.9300",
      longitude: "77.5800",
    },
    telephone: "+91 6361197107",
    email: "drmadhuri.og@gmail.com",
    keywords: [
      "Best maternity clinic in Jayanagar",
      "Best Gynecologist in Jayanagar 7th Block",
      "Diabetes in Pregnancy (GDM) in Jayanagar 7th Block",
      "Best Gynecologist in Jayanagar 4th Block",
      "Best Gynecologist in Jayanagar 9th block",
      "Hormone imbalance treatment in Jayanagar 7th Block",
    ],
    datePublished: "2025-11-28",
    sameAs: ["https://www.drmadhurimsobgyn.com/"],
  },
  "gynaecology/annual-check-ups-and-preventive-screenings": {
    "@context": "https://schema.org",
    "@type": "MedicalClinic",
    "@id":
      "https://www.drmadhurimsobgyn.com/our-services/gynaecology/annual-check-ups-and-preventive-screenings/#clinic",
    name: "Dr Madhuri M S OB-GYN Clinic",
    url: "https://www.drmadhurimsobgyn.com/our-services/gynaecology/annual-check-ups-and-preventive-screenings",
    image: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    logo: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    address: {
      "@type": "PostalAddress",
      streetAddress: "Pattabhirama Nagar, Jayanagar",
      addressLocality: "Bengaluru",
      addressRegion: "Karnataka",
      postalCode: "560041",
      addressCountry: "IN",
    },
    geo: {
      "@type": "GeoCoordinates",
      latitude: "12.9300",
      longitude: "77.5800",
    },
    telephone: "+91 6361197107",
    email: "drmadhuri.og@gmail.com",
    keywords: [
      "Best maternity clinic in Jayanagar",
      "Best Gynecologist in Jayanagar 7th Block",
      "Diabetes in Pregnancy (GDM) in Jayanagar 7th Block",
      "Best Gynecologist in Jayanagar 4th Block",
      "Best Gynecologist in Jayanagar 9th block",
      "best health checkup hospital in Jayanagar",
    ],
    datePublished: "2025-11-28",
    sameAs: ["https://www.drmadhurimsobgyn.com/"],
  },
  "laparoscopy-hysteroscopy": {
    "@context": "https://schema.org",
    "@type": "MedicalClinic",
    "@id": "https://www.drmadhurimsobgyn.com/our-services/laparoscopy-hysteroscopy/#clinic",
    name: "Dr Madhuri M S OB-GYN Clinic",
    url: "https://www.drmadhurimsobgyn.com/our-services/laparoscopy-hysteroscopy",
    image: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    logo: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    address: {
      "@type": "PostalAddress",
      streetAddress: "Pattabhirama Nagar, Jayanagar",
      addressLocality: "Bengaluru",
      addressRegion: "Karnataka",
      postalCode: "560041",
      addressCountry: "IN",
    },
    geo: {
      "@type": "GeoCoordinates",
      latitude: "12.9300",
      longitude: "77.5800",
    },
    telephone: "+91 6361197107",
    email: "drmadhuri.og@gmail.com",
    keywords: [
      "Best maternity clinic in Jayanagar",
      "Best Gynecologist in Jayanagar 7th Block",
      "Diabetes in Pregnancy (GDM) in Jayanagar 7th Block",
      "Best Gynecologist in Jayanagar 4th Block",
      "Best Gynecologist in Jayanagar 9th block",
      "Laparoscopy surgery hospital in Jayanagar 9th Block",
    ],
    datePublished: "2025-11-28",
    sameAs: ["https://www.drmadhurimsobgyn.com/"],
  },
  "laparoscopy-hysteroscopy/diagnostic-hystero-laparoscopy": {
    "@context": "https://schema.org",
    "@type": "MedicalClinic",
    "@id":
      "https://www.drmadhurimsobgyn.com/our-services/laparoscopy-hysteroscopy/diagnostic-hystero-laparoscopy/#clinic",
    name: "Dr Madhuri M S OB-GYN Clinic",
    url: "https://www.drmadhurimsobgyn.com/our-services/laparoscopy-hysteroscopy/diagnostic-hystero-laparoscopy",
    image: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    logo: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    address: {
      "@type": "PostalAddress",
      streetAddress: "Pattabhirama Nagar, Jayanagar",
      addressLocality: "Bengaluru",
      addressRegion: "Karnataka",
      postalCode: "560041",
      addressCountry: "IN",
    },
    geo: {
      "@type": "GeoCoordinates",
      latitude: "12.9300",
      longitude: "77.5800",
    },
    telephone: "+91 6361197107",
    email: "drmadhuri.og@gmail.com",
    keywords: [
      "Best maternity clinic in Jayanagar",
      "Best Gynecologist in Jayanagar 7th Block",
      "Diabetes in Pregnancy (GDM) in Jayanagar 7th Block",
      "Best Gynecologist in Jayanagar 4th Block",
      "Best Gynecologist in Jayanagar 9th block",
      "Infertility specialist in Jayanagar",
    ],
    datePublished: "2025-11-28",
    sameAs: ["https://www.drmadhurimsobgyn.com/"],
  },
  "laparoscopy-hysteroscopy/operative-hystero-laparoscopy": {
    "@context": "https://schema.org",
    "@type": "MedicalClinic",
    "@id":
      "https://www.drmadhurimsobgyn.com/our-services/laparoscopy-hysteroscopy/operative-hystero-laparoscopy/#clinic",
    name: "Dr Madhuri M S OB-GYN Clinic",
    url: "https://www.drmadhurimsobgyn.com/our-services/laparoscopy-hysteroscopy/operative-hystero-laparoscopy",
    image: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    logo: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    address: {
      "@type": "PostalAddress",
      streetAddress: "Pattabhirama Nagar, Jayanagar",
      addressLocality: "Bengaluru",
      addressRegion: "Karnataka",
      postalCode: "560041",
      addressCountry: "IN",
    },
    geo: {
      "@type": "GeoCoordinates",
      latitude: "12.9300",
      longitude: "77.5800",
    },
    telephone: "+91 6361197107",
    email: "drmadhuri.og@gmail.com",
    keywords: [
      "Best maternity clinic in Jayanagar",
      "Best Gynecologist in Jayanagar 7th Block",
      "Diabetes in Pregnancy (GDM) in Jayanagar 7th Block",
      "Best Gynecologist in Jayanagar 4th Block",
      "Best Gynecologist in Jayanagar 9th block",
      "Laparoscopy surgery hospital in Jayanagar 7th block",
    ],
    datePublished: "2025-11-28",
    sameAs: ["https://www.drmadhurimsobgyn.com/"],
  },
  "laparoscopy-hysteroscopy/laparoscopic-myomectomy": {
    "@context": "https://schema.org",
    "@type": "MedicalClinic",
    "@id":
      "https://www.drmadhurimsobgyn.com/our-services/laparoscopy-hysteroscopy/laparoscopic-myomectomy/#clinic",
    name: "Dr Madhuri M S OB-GYN Clinic",
    url: "https://www.drmadhurimsobgyn.com/our-services/laparoscopy-hysteroscopy/laparoscopic-myomectomy",
    image: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    logo: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    address: {
      "@type": "PostalAddress",
      streetAddress: "Pattabhirama Nagar, Jayanagar",
      addressLocality: "Bengaluru",
      addressRegion: "Karnataka",
      postalCode: "560041",
      addressCountry: "IN",
    },
    geo: {
      "@type": "GeoCoordinates",
      latitude: "12.9300",
      longitude: "77.5800",
    },
    telephone: "+91 6361197107",
    email: "drmadhuri.og@gmail.com",
    keywords: [
      "Best maternity clinic in Jayanagar",
      "Best Gynecologist in Jayanagar 7th Block",
      "Diabetes in Pregnancy (GDM) in Jayanagar 7th Block",
      "Best Gynecologist in Jayanagar 4th Block",
      "Best Gynecologist in Jayanagar 9th block",
      "myomectomy specialist in Jayanagar 4th Block",
    ],
    datePublished: "2025-11-28",
    sameAs: ["https://www.drmadhurimsobgyn.com/"],
  },
  "laparoscopy-hysteroscopy/total-laparoscopic-hysterectomy-tlh": {
    "@context": "https://schema.org",
    "@type": "MedicalClinic",
    "@id":
      "https://www.drmadhurimsobgyn.com/our-services/laparoscopy-hysteroscopy/total-laparoscopic-hysterectomy-tlh/#clinic",
    name: "Dr Madhuri M S OB-GYN Clinic",
    url: "https://www.drmadhurimsobgyn.com/our-services/laparoscopy-hysteroscopy/total-laparoscopic-hysterectomy-tlh",
    image: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    logo: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    address: {
      "@type": "PostalAddress",
      streetAddress: "Pattabhirama Nagar, Jayanagar",
      addressLocality: "Bengaluru",
      addressRegion: "Karnataka",
      postalCode: "560041",
      addressCountry: "IN",
    },
    geo: {
      "@type": "GeoCoordinates",
      latitude: "12.9300",
      longitude: "77.5800",
    },
    telephone: "+91 6361197107",
    email: "drmadhuri.og@gmail.com",
    keywords: [
      "Best maternity clinic in Jayanagar",
      "Best Gynecologist in Jayanagar 7th Block",
      "Diabetes in Pregnancy (GDM) in Jayanagar 7th Block",
      "Best Gynecologist in Jayanagar 4th Block",
      "Best Gynecologist in Jayanagar 9th block",
      "Laparoscopy surgery hospital in Byrasandra",
    ],
    datePublished: "2025-11-28",
    sameAs: ["https://www.drmadhurimsobgyn.com/"],
  },
  "laparoscopy-hysteroscopy/diagnostic-hysteroscopy": {
    "@context": "https://schema.org",
    "@type": "MedicalClinic",
    "@id":
      "https://www.drmadhurimsobgyn.com/our-services/laparoscopy-hysteroscopy/diagnostic-hysteroscopy/#clinic",
    name: "Dr Madhuri M S OB-GYN Clinic",
    url: "https://www.drmadhurimsobgyn.com/our-services/laparoscopy-hysteroscopy/diagnostic-hysteroscopy",
    image: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    logo: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    address: {
      "@type": "PostalAddress",
      streetAddress: "Pattabhirama Nagar, Jayanagar",
      addressLocality: "Bengaluru",
      addressRegion: "Karnataka",
      postalCode: "560041",
      addressCountry: "IN",
    },
    geo: {
      "@type": "GeoCoordinates",
      latitude: "12.9300",
      longitude: "77.5800",
    },
    telephone: "+91 6361197107",
    email: "drmadhuri.og@gmail.com",
    keywords: [
      "Best maternity clinic in Jayanagar",
      "Best Gynecologist in Jayanagar 7th Block",
      "Diabetes in Pregnancy (GDM) in Jayanagar 7th Block",
      "Best Gynecologist in Jayanagar 4th Block",
      "Best Gynecologist in Jayanagar 9th block",
      "Diagnostic hysteroscopy in Jayanagar",
    ],
    datePublished: "2025-11-28",
    sameAs: ["https://www.drmadhurimsobgyn.com/"],
  },
  "laparoscopy-hysteroscopy/hysteroscopic-septal-resection": {
    "@context": "https://schema.org",
    "@type": "MedicalClinic",
    "@id":
      "https://www.drmadhurimsobgyn.com/our-services/laparoscopy-hysteroscopy/hysteroscopic-septal-resection/#clinic",
    name: "Dr Madhuri M S OB-GYN Clinic",
    url: "https://www.drmadhurimsobgyn.com/our-services/laparoscopy-hysteroscopy/hysteroscopic-septal-resection",
    image: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    logo: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    address: {
      "@type": "PostalAddress",
      streetAddress: "Pattabhirama Nagar, Jayanagar",
      addressLocality: "Bengaluru",
      addressRegion: "Karnataka",
      postalCode: "560041",
      addressCountry: "IN",
    },
    geo: {
      "@type": "GeoCoordinates",
      latitude: "12.9300",
      longitude: "77.5800",
    },
    telephone: "+91 6361197107",
    email: "drmadhuri.og@gmail.com",
    keywords: [
      "Best maternity clinic in Jayanagar",
      "Best Gynecologist in Jayanagar 7th Block",
      "Diabetes in Pregnancy (GDM) in Jayanagar 7th Block",
      "Best Gynecologist in Jayanagar 4th Block",
      "Best Gynecologist in Jayanagar 9th block",
      "Hysteroscopy hospital near Jayanagar",
    ],
    datePublished: "2025-11-28",
    sameAs: ["https://www.drmadhurimsobgyn.com/"],
  },
  "laparoscopy-hysteroscopy/hysteroscopic-polypectomy": {
    "@context": "https://schema.org",
    "@type": "MedicalClinic",
    "@id":
      "https://www.drmadhurimsobgyn.com/our-services/laparoscopy-hysteroscopy/hysteroscopic-polypectomy/#clinic",
    name: "Dr Madhuri M S OB-GYN Clinic",
    url: "https://www.drmadhurimsobgyn.com/our-services/laparoscopy-hysteroscopy/hysteroscopic-polypectomy",
    image: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    logo: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    address: {
      "@type": "PostalAddress",
      streetAddress: "Pattabhirama Nagar, Jayanagar",
      addressLocality: "Bengaluru",
      addressRegion: "Karnataka",
      postalCode: "560041",
      addressCountry: "IN",
    },
    geo: {
      "@type": "GeoCoordinates",
      latitude: "12.9300",
      longitude: "77.5800",
    },
    telephone: "+91 6361197107",
    email: "drmadhuri.og@gmail.com",
    keywords: [
      "Best maternity clinic in Jayanagar",
      "Best Gynecologist in Jayanagar 7th Block",
      "Diabetes in Pregnancy (GDM) in Jayanagar 7th Block",
      "Best Gynecologist in Jayanagar 4th Block",
      "Best Gynecologist in Jayanagar 9th block",
      "Best gynecologist for uterine polyps in Jayanagar",
    ],
    datePublished: "2025-11-28",
    sameAs: ["https://www.drmadhurimsobgyn.com/"],
  },
  "laparoscopy-hysteroscopy/tubal-re-canalisation": {
    "@context": "https://schema.org",
    "@type": "MedicalClinic",
    "@id":
      "https://www.drmadhurimsobgyn.com/our-services/laparoscopy-hysteroscopy/tubal-re-canalisation/#clinic",
    name: "Dr Madhuri M S OB-GYN Clinic",
    url: "https://www.drmadhurimsobgyn.com/our-services/laparoscopy-hysteroscopy/tubal-re-canalisation",
    image: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    logo: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    address: {
      "@type": "PostalAddress",
      streetAddress: "Pattabhirama Nagar, Jayanagar",
      addressLocality: "Bengaluru",
      addressRegion: "Karnataka",
      postalCode: "560041",
      addressCountry: "IN",
    },
    geo: {
      "@type": "GeoCoordinates",
      latitude: "12.9300",
      longitude: "77.5800",
    },
    telephone: "+91 6361197107",
    email: "drmadhuri.og@gmail.com",
    keywords: [
      "Best maternity clinic in Jayanagar",
      "Best Gynecologist in Jayanagar 7th Block",
      "Diabetes in Pregnancy (GDM) in Jayanagar 7th Block",
      "Best Gynecologist in Jayanagar 4th Block",
      "Best Gynecologist in Jayanagar 9th block",
      "Tubal recanalisation in Jayanagar 7th Block",
    ],
    datePublished: "2025-11-29",
    sameAs: ["https://www.drmadhurimsobgyn.com/"],
  },
  "laparoscopy-hysteroscopy/chromopertubation": {
    "@context": "https://schema.org",
    "@type": "MedicalClinic",
    "@id":
      "https://www.drmadhurimsobgyn.com/our-services/laparoscopy-hysteroscopy/chromopertubation/#clinic",
    name: "Dr Madhuri M S OB-GYN Clinic",
    url: "https://www.drmadhurimsobgyn.com/our-services/laparoscopy-hysteroscopy/chromopertubation",
    image: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    logo: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    address: {
      "@type": "PostalAddress",
      streetAddress: "Pattabhirama Nagar, Jayanagar",
      addressLocality: "Bengaluru",
      addressRegion: "Karnataka",
      postalCode: "560041",
      addressCountry: "IN",
    },
    geo: {
      "@type": "GeoCoordinates",
      latitude: "12.9300",
      longitude: "77.5800",
    },
    telephone: "+91 6361197107",
    email: "drmadhuri.og@gmail.com",
    keywords: [
      "Best maternity clinic in Jayanagar",
      "Best Gynecologist in Jayanagar 7th Block",
      "Diabetes in Pregnancy (GDM) in Jayanagar 7th Block",
      "Best Gynecologist in Jayanagar 4th Block",
      "Best Gynecologist in Jayanagar 9th block",
      "Infertility specialist in Jayanagar 9th Block",
    ],
    datePublished: "2025-11-29",
    sameAs: ["https://www.drmadhurimsobgyn.com/"],
  },
  "laparoscopy-hysteroscopy/laparoscopic-ovarian-cystectomy": {
    "@context": "https://schema.org",
    "@type": "MedicalClinic",
    "@id":
      "https://www.drmadhurimsobgyn.com/our-services/laparoscopy-hysteroscopy/laparoscopic-ovarian-cystectomy/#clinic",
    name: "Dr Madhuri M S OB-GYN Clinic",
    url: "https://www.drmadhurimsobgyn.com/our-services/laparoscopy-hysteroscopy/laparoscopic-ovarian-cystectomy",
    image: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    logo: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    address: {
      "@type": "PostalAddress",
      streetAddress: "Pattabhirama Nagar, Jayanagar",
      addressLocality: "Bengaluru",
      addressRegion: "Karnataka",
      postalCode: "560041",
      addressCountry: "IN",
    },
    geo: {
      "@type": "GeoCoordinates",
      latitude: "12.9300",
      longitude: "77.5800",
    },
    telephone: "+91 6361197107",
    email: "drmadhuri.og@gmail.com",
    keywords: [
      "Best maternity clinic in Jayanagar",
      "Best Gynecologist in Jayanagar 7th Block",
      "Diabetes in Pregnancy (GDM) in Jayanagar 7th Block",
      "Best Gynecologist in Jayanagar 4th Block",
      "Best Gynecologist in Jayanagar 9th block",
      "Ovarian cyst treatment in Jayanagar 4th Block",
    ],
    datePublished: "2025-11-29",
    sameAs: ["https://www.drmadhurimsobgyn.com/"],
  },
  "laparoscopy-hysteroscopy/tubal-clipping-hydrosalpinx": {
    "@context": "https://schema.org",
    "@type": "MedicalClinic",
    "@id":
      "https://www.drmadhurimsobgyn.com/our-services/laparoscopy-hysteroscopy/tubal-clipping-hydrosalpinx/#clinic",
    name: "Dr Madhuri M S OB-GYN Clinic",
    url: "https://www.drmadhurimsobgyn.com/our-services/laparoscopy-hysteroscopy/tubal-clipping-hydrosalpinx",
    image: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    logo: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    address: {
      "@type": "PostalAddress",
      streetAddress: "Pattabhirama Nagar, Jayanagar",
      addressLocality: "Bengaluru",
      addressRegion: "Karnataka",
      postalCode: "560041",
      addressCountry: "IN",
    },
    geo: {
      "@type": "GeoCoordinates",
      latitude: "12.9300",
      longitude: "77.5800",
    },
    telephone: "+91 6361197107",
    email: "drmadhuri.og@gmail.com",
    keywords: [
      "Best maternity clinic in Jayanagar",
      "Best Gynecologist in Jayanagar 7th Block",
      "Diabetes in Pregnancy (GDM) in Jayanagar 7th Block",
      "Best Gynecologist in Jayanagar 4th Block",
      "Best Gynecologist in Jayanagar 9th block",
      "Tubal clipping treatment in Jayanagar 9th Block",
    ],
    datePublished: "2025-11-29",
    sameAs: ["https://www.drmadhurimsobgyn.com/"],
  },
  "laparoscopy-hysteroscopy/laparoscopic-tubal-occlusion-permanent-sterilization": {
    "@context": "https://schema.org",
    "@type": "MedicalClinic",
    "@id":
      "https://www.drmadhurimsobgyn.com/our-services/laparoscopy-hysteroscopy/laparoscopic-tubal-occlusion-permanent-sterilization/#clinic",
    name: "Dr Madhuri M S OB-GYN Clinic",
    url: "https://www.drmadhurimsobgyn.com/our-services/laparoscopy-hysteroscopy/laparoscopic-tubal-occlusion-permanent-sterilization",
    image: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    logo: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    address: {
      "@type": "PostalAddress",
      streetAddress: "Pattabhirama Nagar, Jayanagar",
      addressLocality: "Bengaluru",
      addressRegion: "Karnataka",
      postalCode: "560041",
      addressCountry: "IN",
    },
    geo: {
      "@type": "GeoCoordinates",
      latitude: "12.9300",
      longitude: "77.5800",
    },
    telephone: "+91 6361197107",
    email: "drmadhuri.og@gmail.com",
    keywords: [
      "Best maternity clinic in Jayanagar",
      "Best Gynecologist in Jayanagar 7th Block",
      "Diabetes in Pregnancy (GDM) in Jayanagar 7th Block",
      "Best Gynecologist in Jayanagar 4th Block",
      "Best Gynecologist in Jayanagar 9th block",
      "Laparoscopy surgery hospital in Jayanagar 4th Block",
    ],
    datePublished: "2025-11-29",
    sameAs: ["https://www.drmadhurimsobgyn.com/"],
  },
  ultrasonography: {
    "@context": "https://schema.org",
    "@type": "MedicalClinic",
    "@id": "https://www.drmadhurimsobgyn.com/our-services/ultrasonography/#clinic",
    name: "Dr Madhuri M S OB-GYN Clinic",
    url: "https://www.drmadhurimsobgyn.com/our-services/ultrasonography",
    image: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    logo: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    address: {
      "@type": "PostalAddress",
      streetAddress: "Pattabhirama Nagar, Jayanagar",
      addressLocality: "Bengaluru",
      addressRegion: "Karnataka",
      postalCode: "560041",
      addressCountry: "IN",
    },
    geo: {
      "@type": "GeoCoordinates",
      latitude: "12.9300",
      longitude: "77.5800",
    },
    telephone: "+91 6361197107",
    email: "drmadhuri.og@gmail.com",
    keywords: [
      "Best maternity clinic in Jayanagar",
      "Best Gynecologist in Jayanagar 7th Block",
      "Diabetes in Pregnancy (GDM) in Jayanagar 7th Block",
      "Best Gynecologist in Jayanagar 4th Block",
      "Best Gynecologist in Jayanagar 9th block",
      "Ultrasound scan center in Jayanagar 7th Block",
    ],
    datePublished: "2025-11-29",
    sameAs: ["https://www.drmadhurimsobgyn.com/"],
  },
  "ultrasonography/transvaginal-scan": {
    "@context": "https://schema.org",
    "@type": "MedicalClinic",
    "@id":
      "https://www.drmadhurimsobgyn.com/our-services/ultrasonography/transvaginal-scan/#clinic",
    name: "Dr Madhuri M S OB-GYN Clinic",
    url: "https://www.drmadhurimsobgyn.com/our-services/ultrasonography/transvaginal-scan",
    image: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    logo: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    address: {
      "@type": "PostalAddress",
      streetAddress: "Pattabhirama Nagar, Jayanagar",
      addressLocality: "Bengaluru",
      addressRegion: "Karnataka",
      postalCode: "560041",
      addressCountry: "IN",
    },
    geo: {
      "@type": "GeoCoordinates",
      latitude: "12.9300",
      longitude: "77.5800",
    },
    telephone: "+91 6361197107",
    email: "drmadhuri.og@gmail.com",
    keywords: [
      "Best maternity clinic in Jayanagar",
      "Best Gynecologist in Jayanagar 7th Block",
      "Diabetes in Pregnancy (GDM) in Jayanagar 7th Block",
      "Best Gynecologist in Jayanagar 4th Block",
      "Best Gynecologist in Jayanagar 9th block",
      "Ultrasound test near me",
    ],
    datePublished: "2025-11-29",
    sameAs: ["https://www.drmadhurimsobgyn.com/"],
  },
  "ultrasonography/saline-sonography": {
    "@context": "https://schema.org",
    "@type": "MedicalClinic",
    "@id":
      "https://www.drmadhurimsobgyn.com/our-services/ultrasonography/saline-sonography/#clinic",
    name: "Dr Madhuri M S OB-GYN Clinic",
    url: "https://www.drmadhurimsobgyn.com/our-services/ultrasonography/saline-sonography",
    image: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    logo: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    address: {
      "@type": "PostalAddress",
      streetAddress: "Pattabhirama Nagar, Jayanagar",
      addressLocality: "Bengaluru",
      addressRegion: "Karnataka",
      postalCode: "560041",
      addressCountry: "IN",
    },
    geo: {
      "@type": "GeoCoordinates",
      latitude: "12.9300",
      longitude: "77.5800",
    },
    telephone: "+91 6361197107",
    email: "drmadhuri.og@gmail.com",
    keywords: [
      "Best maternity clinic in Jayanagar",
      "Best Gynecologist in Jayanagar 7th Block",
      "Diabetes in Pregnancy (GDM) in Jayanagar 7th Block",
      "Best Gynecologist in Jayanagar 4th Block",
      "Best Gynecologist in Jayanagar 9th block",
      "Best Ultrasound scan center in Jayanagar 4th Block",
    ],
    datePublished: "2025-11-29",
    sameAs: ["https://www.drmadhurimsobgyn.com/"],
  },
  "ultrasonography/3d-ultrasonography": {
    "@context": "https://schema.org",
    "@type": "MedicalClinic",
    "@id":
      "https://www.drmadhurimsobgyn.com/our-services/ultrasonography/3d-ultrasonography/#clinic",
    name: "Dr Madhuri M S OB-GYN Clinic",
    url: "https://www.drmadhurimsobgyn.com/our-services/ultrasonography/3d-ultrasonography",
    image: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    logo: "https://www.drmadhurimsobgyn.com/assets/home-image/Dr%20Madhurilogo.png",
    address: {
      "@type": "PostalAddress",
      streetAddress: "Pattabhirama Nagar, Jayanagar",
      addressLocality: "Bengaluru",
      addressRegion: "Karnataka",
      postalCode: "560041",
      addressCountry: "IN",
    },
    geo: {
      "@type": "GeoCoordinates",
      latitude: "12.9300",
      longitude: "77.5800",
    },
    telephone: "+91 6361197107",
    email: "drmadhuri.og@gmail.com",
    keywords: [
      "Best maternity clinic in Jayanagar",
      "Best Gynecologist in Jayanagar 7th Block",
      "Diabetes in Pregnancy (GDM) in Jayanagar 7th Block",
      "Best Gynecologist in Jayanagar 4th Block",
      "Best Gynecologist in Jayanagar 9th block",
      "3D Ultrasound scan center in Jayanagar 9th Block",
    ],
    datePublished: "2025-11-29",
    sameAs: ["https://www.drmadhurimsobgyn.com/"],
  },
};

export default function Head({ params }) {
  const segs = Array.isArray(params?.["sub-services"]) ? params["sub-services"] : [];
  const pathKey = segs.join("/");
  const jsonLd = schemaMap[pathKey];

  if (!jsonLd) return null;

  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
    />
  );
}
